export const data = [
    "You've used all of the storage that's available in your Google Account. As a result, you may not be able to send and receive emails on your Gmail account and you won't be able to upload new files to Google Drive and Google Photos. Get more storage now with a Google One membership. Plans start at BDT 150.00 a month. "
    ,"You've used all of the storage that's available in your Google Account. As a result, you may not be able to send and receive emails on your Gmail account and you won't be able to upload new files to Google Drive and Google Photos. Get more storage now with a Google One membership. Plans start at BDT 150.00 a month. "
    ,"You've used all of the storage that's available in your Google Account. As a result, you may not be able to send and receive emails on your Gmail account and you won't be able to upload new files to Google Drive and Google Photos. Get more storage now with a Google One membership. Plans start at BDT 150.00 a month. "
    ,"You've used all of the storage that's available in your Google Account. As a result, you may not be able to send and receive emails on your Gmail account and you won't be able to upload new files to Google Drive and Google Photos. Get more storage now with a Google One membership. Plans start at BDT 150.00 a month. "
    ,"You've used all of the storage that's available in your Google Account. As a result, you may not be able to send and receive emails on your Gmail account and you won't be able to upload new files to Google Drive and Google Photos. Get more storage now with a Google One membership. Plans start at BDT 150.00 a month. "
    ,"You've used all of the storage that's available in your Google Account. As a result, you may not be able to send and receive emails on your Gmail account and you won't be able to upload new files to Google Drive and Google Photos. Get more storage now with a Google One membership. Plans start at BDT 150.00 a month. "
    ,"You've used all of the storage that's available in your Google Account. As a result, you may not be able to send and receive emails on your Gmail account and you won't be able to upload new files to Google Drive and Google Photos. Get more storage now with a Google One membership. Plans start at BDT 150.00 a month. "
    ,"You've used all of the storage that's available in your Google Account. As a result, you may not be able to send and receive emails on your Gmail account and you won't be able to upload new files to Google Drive and Google Photos. Get more storage now with a Google One membership. Plans start at BDT 150.00 a month. "
    ,"You've used all of the storage that's available in your Google Account. As a result, you may not be able to send and receive emails on your Gmail account and you won't be able to upload new files to Google Drive and Google Photos. Get more storage now with a Google One membership. Plans start at BDT 150.00 a month. "
    ,"You've used all of the storage that's available in your Google Account. As a result, you may not be able to send and receive emails on your Gmail account and you won't be able to upload new files to Google Drive and Google Photos. Get more storage now with a Google One membership. Plans start at BDT 150.00 a month. "
    ,"You've used all of the storage that's available in your Google Account. As a result, you may not be able to send and receive emails on your Gmail account and you won't be able to upload new files to Google Drive and Google Photos. Get more storage now with a Google One membership. Plans start at BDT 150.00 a month. "
    ,"You've used all of the storage that's available in your Google Account. As a result, you may not be able to send and receive emails on your Gmail account and you won't be able to upload new files to Google Drive and Google Photos. Get more storage now with a Google One membership. Plans start at BDT 150.00 a month. "
    
];
